### ISSUE TITLE
In REPS, looks like  ‘select’ don't work in code

### ISSUE THREAD

**Issue by Hessen525** [Yang890912/QuantumRouting-python#3]
Thanks for your nice code， it helps me a lot！ I have a question as follows.
 

https://github.com/Yang890912/QuantumRouting-python/blob/8fb511506ab9e53ddde0c99dcf25a94a0458ae25/src/quantum/algorithm/REPS.py#L428

this line seems different from the original in the paper. The original statement is not very clear to me， so I am not very sure  

![image](https://user-images.githubusercontent.com/25447481/167237261-3fe9d7d5-894e-49d4-ae7a-0f3541b596c0.png)

**Comment by 510117** [comment]
I'm the author of REPS.py, and you are correct it shoud be ```self.tki_LP[SDpair][k]```, ```tki_LP``` is float between `0` to `1` because relaxed version in EPS line2.
And I guess the ```Pki(r)``` is the width of Path according to ```fki_LP(u, v)```, I'm not sure too.

**Comment by Hessen525** [comment]
@510117  Got them，Thanks for your reply！
