### ISSUE TITLE
Why run self.fi_LP[SDpair][(node, next)] -= width twice in PFT function of REPS.PY?

### ISSUE THREAD

**Issue by Hessen525** [Yang890912/QuantumRouting-python#4]
Hi, it looks like you tried twice, could you please tell me the reason? 
1. https://github.com/Hessen525/QuantumRouting-python/blob/5f8e16e0aa0eb7adcd809f61e4a189ba1e543438/src/quantum/algorithm/REPS.py#L596
2. https://github.com/Hessen525/QuantumRouting-python/blob/5f8e16e0aa0eb7adcd809f61e4a189ba1e543438/src/quantum/algorithm/REPS.py#L231

**Comment by 510117** [comment]
Oh, It seems that the line 231 is redundant. Because `self.fi_LP[SDpair][(node, next)]` will recalculate in next round.
Thank you for debug.

**Comment by 510117** [comment]
I pushed but I'm not 100 percent sure.
You can take a look.
